### ISSUE TITLE
breaks html and mutated vowel

### ISSUE THREAD

**Issue by oll1** [Gumball12/bionic-reading#11]

**Comment by Gumball12** [comment]
Hi. Thanks for leaving the issue.
Can you provide more details? (test cases, expected results, and actual outputs, etc.)

**Comment by r3wt** [comment]
@oll1 it would be very helpful if you could provide details and a simple reproduction, to allow the maintainer to provide a fix for this issue. This is a big part of open source, developers get feedback from the community and it helps to mature the product into a reliable software.

**Comment by Gumball12** [comment]
@oll1 
There is no answer, so I will close the issue for now. However, if you find a bug in the future, please open the issue again or create a new one. Thank you.
