### ISSUE TITLE
Doesn't respect punctuation; doesn't match output of bionic website

### ISSUE THREAD

**Issue by r3wt** [Gumball12/bionic-reading#12]
I wanted to more closely match the formatting of the demo on bionic-typings website, this is what i came up with. it also ignores punctuation. perhaps you can adapt this to your library. cheers
```js
const bionicWordSplit = (word) => {
  const { length } = word;
  let splitPoint;
  switch(true) {
    case length<=4:
      splitPoint = length-1;
    break;
    default:
      splitPoint = length-2; 
    break;
  }
  const first = word.slice(0, splitPoint);
  const second = word.slice(splitPoint);

  return [first, second];
};

function splitParagraphs( str ) {
  return str.split("\n").map(paragraph=>paragraph.replace("\r",""));
}

function unrollToIntermediateStructure( text ) {
  const paragraphs = splitParagraphs(text);
  const exp = /(\w+)/g;
  return paragraphs.map(paragraph=>{
    return paragraph.split(exp).map(item=>{
      if(item.includes('!')||item===' '||item.includes('?')||item.includes('.')||item.includes(',')||item===""){
        return item;
      }
      return bionicWordSplit(item);  
    })
  });
}

function format( intermediateStructure, formatWordFn ) {
  return intermediateStructure.map(paragraphs=>paragraphs.map(item=>Array.isArray(item)?formatWordFn(item):item).join("")).join("\n");
}

function htmlFormatter([start,end]) {
  return `<strong>${start}</strong>${end}`;
}

function markdownFormatter([start,end]) {
  return `**${start}**${end}`;
}

const test = 'Welcome to bionic reading. This will teach you how to read and write in bionic style. I am not sure how this algorithm works. Walking, running, jumping, standing all can be achieved with supreme grace and wonderous accuracy.';

const intermediate = unrollToIntermediateStructure(test);
const htmlResult = format(intermediate,htmlFormatter);
const markdownResult = format(intermediate,markdownFormatter);

console.log(intermediate);
console.log(htmlResult);
console.log(markdownResult);
```

**Comment by Gumball12** [comment]
Thanks for leaving the issue.
As you mentioned, the current bionic-reading npm module was a bit far from the actual bionic-reading API.
I'll soon apply this logic to the module to improve it. Thank you.

**Comment by r3wt** [comment]
@Gumball12 NP, look forward to seeing the development of your library, and using it in my projects 😁

**Comment by Gumball12** [comment]
Thanks for your comments. This idea allowed me to improve it to achieve almost the same results as the Bionic-Reading API.

**Comment by r3wt** [comment]
Good job, it looks great. cant wait to test it out 🤙. one thing i thought about was acronymn's which use `.` as delineator, such as `S.W.A.T.`, and also Roman Numerals with or without `.` postfix. I havent had a chance to test either against bionic API yet (currently recovering from surgery) but thought it was worth mentioning to you. On Thu, May 26, 2022 at 12:33 PM shj ***@***.***> wrote:
Thanks for your comments. This idea allowed me to improve it to achieve almost the same results as the Bionic-Reading API.
