### ISSUE TITLE
Bionic Reading® Legal Stuff 

### ISSUE THREAD

**Issue by jomamaaye** [Gumball12/bionic-reading#27]
This isn't a bug, but I just want to inform y'all that the wonderful® folks at Bionic Reading® have decided to crack down on any open source projects that involves Bionic Reading®. It is advised to remove all mentioning of Bionic Reading® for now to avoid legal repercussions.

Context
<img width="746" alt="legal notice" src="https://user-images.githubusercontent.com/106170863/171382672-45896e09-5075-4345-a73e-981f03807c17.png">

**Comment by Gumball12** [comment]
Thank you for the information. I'll fix it soon.

**Comment by KyahWill** [comment]
My suggestion would be to probably use the name "Vide" from latin meaning see

**Comment by Gumball12** [comment]
@KyahWill 
That's a good idea. I will refer to it. Thank you 🙂
