### ISSUE TITLE
Add support for emojis

### ISSUE THREAD

**Issue by pranava-mohan** [Gumball12/bionic-reading#28]
Consider this;
```
const { bionicReading } = require("bionic-reading");

console.log(bionicReading("👆 hello there, this is some dummy text"));
```

When I run it, the emoji seems to break:
```
"<b>�</b>� <b>hel</b>lo <b>the</b>re, <b>thi</b>s <b>i</b>s <b>som</b>e <b>dum</b>my <b>tex</b>t"
```
![bionic-issue](https://user-images.githubusercontent.com/71634384/171604826-aeff72f8-acce-4717-9bbc-65eba8abb9ed.png)

Please fix this ASAP!

**Comment by Gumball12** [comment]
Hi. Thank you for leaving this issue.
I checked and I will try to fix it as soon as possible 🙂
