### ISSUE TITLE
Hello I want to ask a question

### ISSUE THREAD

**Issue by elitetrollz** [Gumball12/bionic-reading#35]
Hi. I'm new to coding. Is this possible to implement with a ChakraUI library for converting text to bionic reading?

Also, I'm not sure if this is the right place to ask.

**Comment by KyahWill** [comment]
You might need to override the component you need for bionic reading.

**Comment by Gumball12** [comment]
@elitetrollz 
Hi. Thanks for leaving a question.

I'm sorry, but I don't understand the question, do you want to use this module as a component?

Like this -> https://codesandbox.io/s/festive-stonebraker-ij329x

**Comment by Gumball12** [comment]
@elitetrollz 
Was the answer helpful?
If you have any other questions, please create a new issue or reopen this issue. Thank you.
