### ISSUE TITLE
Ignore HTML tags in source text

### ISSUE THREAD

**Issue by teak** [Gumball12/bionic-reading#36]
Would be nice if TextVide had an option to ignore HTML tags in the source text.

I have a source text that is an HTML string, previously rendered from markdown. The only way I have been able to use TextVide is by using jquery to render the HTML, looping over each tag, and running TextVide on each individual text node. Very inelegant and probably inefficient.

Also as a bonus feature it would be good to be able to provide a blacklist of specific tags to exclude their content from TextVide, for example existing `<b>` or `<strong>` tags.

**Comment by Gumball12** [comment]
Hi. Thanks for posting this issue. But it seems difficult to add this feature to the module. sorry.

Text-Vide module focuses on implementing the Bionic Reading API for use in JavaScript. I think it is inappropriate to put any other additional features here.

Even if implemented, I don't think it's going to be very different from the way you mentioned, as the removed (ignored) characters have to be restored. Instead, it seems appropriate to handle it somewhere that uses the Text-Vide module.

Sorry for not giving you the answer you want.

**Comment by teak** [comment]
Perhaps the ability to provide a regex and any matches could be ignored?

I will also point out that the official Bionic Reading API does accept HTML content and correctly parses it.

**Comment by Gumball12** [comment]
I just checked... you're right. I've seen the HTML code removed and Bionic Reading applied only to the actual string. I'll find a way to fix this.

However, I can't devote time to this module because of my job, so I hope you understand even if it's a little late. Or maybe it would be very helpful if you could implement a simpler version of that logic.

- [x] Apply the Bionic Reading technique without HTML code

**Comment by teak** [comment]
I had a quick look at your source, your right it does not seem to be a simple change. I think how I would implement it would be to create a separate function (not an option on the main) and use an HTML parsing library like 'htmlparser2' to preprocess the text.

**Comment by Gumball12** [comment]
@teak 
Hi. It's me again. I just implemented a function that ignores HTML tags([v1.6.0](https://github.com/Gumball12/text-vide/releases/tag/v1.6.0)). A little late, but can you confirm that it is [working properly](https://tinyurl.com/45f8zk2w)?

Note: The Bionic-Reading API ignores HTML tags by default, so this module also ignores tags by default. I just made it possible to include tags using an optional value ([`ignoreHtmlTag`](https://github.com/Gumball12/text-vide#ignorehtmltag)).

**Comment by teak** [comment]
Hey thank you for getting this done, honestly not 'late' at all. So far it is all working great. If all goes well we'll be adding this as an optional accessibility feature in our education app.
