### ISSUE TITLE
Ignore element tags, i.e. `<a ... >`

### ISSUE THREAD

**Issue by jdc-pub** [Gumball12/bionic-reading#37]
Is there any supported way to ignore element tags, like links? For example...

```js
textVide('<a href="https://en.wikipedia.org/wiki/All_models_are_wrong" target="_blank">quote</a>)
```

outputs...

```js
<a href="https://en.wikipedia.org/wiki/All_models_are_wrong" target="_blank"><b>qu</b>ote</a>
```

**Comment by Gumball12** [comment]
I'm sorry, but I don't understand. Do you want the option to ignore certain tags?
Please tell me what kind of results the code below should show.

```ts
textVide('<a href="https://en.wikipedia.org/wiki/All_models_are_wrong" target="_blank">quote</a>')
```

Currently, it looks like the following:

```html
<a href="https://en.wikipedia.org/wiki/All_models_are_wrong" target="_blank"><b>quo</b>te</a>
```

[Sandbox link](https://gumball12.github.io/text-vide/?firstSep=%3Cb%3E&secondSep=%3C%2Fb%3E&fixationPoint=3&input=%3Ca%20href%3D%22https%3A%2F%2Fen.wikipedia.org%2Fwiki%2FAll_models_are_wrong%22%20target%3D%22_blank%22%3Equote%3C%2Fa%3E&ignoreHtmlTag=1)

**Comment by jdc-pub** [comment]
Oh, apologies. I think I misunderstood the `ignoreHtmlTag` option. I'm using this library as part of a blog. I am currently only applying `textVide` to `p` tags. 

I _was_ writing to see if there was a way to ignore certain tags. I wanted the output to read `<a href="https://en.wikipedia.org/wiki/All_models_are_wrong" target="_blank">quote</a>` since the word `quote` is inside the `a` tag. 

But now I that I understand the `ignoreHtmlTag` option better, this kind of tag-ignoring logic probably belongs in the calling code. So instead of applying `textVide` to every `p` tag, I'll apply `textVide` to every `#text` tag that is within `p`, or something like that.

Excellent library, thank you for your work and your quick response!

**Comment by Gumball12** [comment]
Thank you for using it, too!
