### ISSUE TITLE
Add ignoreHtmlEntities

### ISSUE THREAD

**Issue by pftnhr** [Gumball12/bionic-reading#45]
**Is your feature request related to a problem? Please describe.**
I noticed that HTML entities such as `&nbsp;` are not ignored.

**Describe the solution you'd like**
I would be happy if HTML entities such as `&nbsp;` were ignored, just as the HTML tags are ignored. It might be possible to filter for strings that start with a `&` and end with a `;` without a space in between.

**Describe alternatives you've considered**
I can't think of an alternative.

**Additional context**
<img width="558" alt="Screenshot 2023-11-09 um 17 03 40" src="https://github.com/Gumball12/text-vide/assets/7520987/bc272d93-ae22-47e6-aac0-5fb872d90bcd">

At this point, I cannot intervene in the code, as a change would be undone with the next update of the CMS.

**Comment by Gumball12** [comment]
Hi, thank you for your interest in this project.

I think what you've suggested is a really good feature. I'll try to dev it quickly.

**Comment by Gumball12** [comment]
@pftnhr 

Done! You can now use the `ignoreHtmlEntity` option in [text-vide@1.8.0](https://github.com/Gumball12/text-vide/releases/tag/v1.8.0) as shown below([doc](https://github.com/Gumball12/text-vide#ignorehtmlentity)).

```ts
textVide('&nbsp;abcd&gt;'); // '&nbsp;<b>abc</b>d&gt;'
textVide('&nbsp;abcd&gt;', { ignoreHtmlEntity: false }); // &<b>nbs</b>p;<b>abc</b>d&<b>g</b>t;
```

You can also see this in the [sandbox](https://gumball12.github.io/text-vide/?firstSep=%3Cb%3E&secondSep=%3C%2Fb%3E&fixationPoint=1&input=1.%20%26nbsp%3Babcd%26gt%3B%0A2.%20%26nbsp%3Babcd%26gt%3B%0A3.%20%26nbsp%3Babcd%26gt%3B&ignoreHtmlTag=1&ignoreHtmlEntity=1).

Note that it is not named `ignoreHtmlEntities`.

**Comment by Gumball12** [comment]
If you have any additions, or if something doesn't seem to be working, please reopen this issue. Thanks for using this package!

**Comment by pftnhr** [comment]
Now There's a problem with the CDN. The link provided isn't working: https://cdn.jsdelivr.net/npm/text-vide@1.6.2/dist/index.iife.js

**Comment by Gumball12** [comment]
@pftnhr 
Oh my goodness, thanks for the report. I found the reason and will fix it right away.

**Comment by pftnhr** [comment]
I changed the version to 1.8.0 and it works: https://cdn.jsdelivr.net/npm/text-vide@1.8.0/dist/index.iife.js

**Comment by Gumball12** [comment]
@pftnhr 
The README documentation was incorrect until now. Thanks so much for pointing this out. I'll fix the documentation now, thanks!
